### ISSUE TITLE
refine config file

### ISSUE THREAD

**Issue by bjwswang** [bestchains/bc-cli#19]
Previous bc-cli config file https://github.com/bestchains/bc-cli/issues/3#issuecomment-1537057796

```yaml
auth:
    enable: false  # 是否启用oidc验证，也可通过 --enable-auth 参数修改
    expiry: 1683428084  # oidc token过期时间unix时间戳
    idtoken: eyJhbGciOiJSUzI1NiIsImtpZCI6ImVlZWIyZWUyNzA4ZjU0ZDRkODhjMTMyMzllY2EwYzc2NjM1ODE4NDgifQ.eyJpc3MiOiJodHRwczovL3BvcnRhbC4xNzIuMjIuOTYuMjA5Lm5pcC5pby9vaWRjIiwic3ViIjoiQ2doaWFuZHpkMkZ1WnhJR2F6aHpZM0prIiwiYXVkIjoiYmMtY2xpIiwiZXhwIjoxNjgzNDI3ODY2LCJpYXQiOjE2ODMzNDE0NjYsImF0X2hhc2giOiJxdGhPcmgwa2t1VzRUMDY0MDZwZ1pRIiwiY19oYXNoIjoiejBhczN6MW9QcFJOallvM1JtVWpPZyIsImVtYWlsIjoiYWRtaW5AdGVueGNsb3VkLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJncm91cHMiOlsiaWFtLnRlbnhjbG91ZC5jb20iLCJvYnNldmFiaWxpdHkiLCJyZXNvdXJjZS1yZWFkZXIiLCJiZXN0Y2hhaW5zIl0sIm5hbWUiOiJiandzd2FuZyIsInByZWZlcnJlZF91c2VybmFtZSI6ImJqd3N3YW5nIiwicGhvbmUiOiIiLCJ1c2VyaWQiOiJiandzd2FuZyJ9.OoRvS8lTV5T7hX6IXTIzt9Ne-A44ix10-sYbKOg1Bfk7VX3_WaueMDFjALC7qJ5PZG-m6k_iQZn8dSOgMihwMQAfzJxxpoRbWABSJBS72UZSB18zZKK4mLPKAcEtZUYPFcuQhbR9r12FnokvNnEdd6BrWaIIEGQaYrJgix2HQRdDd6t8s-V3et0dvuWrYLv8HiD06KBUUYNnt1SCI6kuzbzpTLNQFNU86mS7Uq58PmXwXp_MwXZ_PnvmV_GDmg5eEgNLPRmXXryvc4o6Bp_FY5GR8amDqKMwt0m6MWhMOPH2ucYppCi7cUsns-z5068vhDrmTDjguQ6lmwC1m8k-0w
    issuerurl: https://portal.172.22.96.209.nip.io/oidc
    refreshtoken: ChllY3N2a2d6dTM3d2Qzc2F6dnhxb3Q0NHIzEhlhaTZiYnQ0eWZoN3NzcGpjamIyZ2N6eWZ1
saas:
    depository:
        server: https://bc-saas.172.22.96.209.nip.io
```

The kubeconfig file
```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM2VENDQWRHZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQ0FYRFRJeE1URXdOREE1TXpFd01sb1lEekl4TWpFeE1ERXhNRGt6TVRBeVdqQVZNUk13RVFZRApWUVFERXdwcmRXSmxjbTVsZEdWek1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBCnVZZGFoYmZpNi9PWkJBRXNoNFVDQkxTdlBqN1FLY2plTS9hZzdtTHkzYXpzYjhKUkMySGFmajNEOFFydmx1c3UKU3MyelVwVlRPTHFBVUV1Nm1sU2FvSFZySkhPeG12anN1bDlOMGg3VG1kN2l1ZE9DZ1VwMG9HV0I0d0hLQnNDMgp6SUJHaEdIUUhkMmdLc1V6MmRwTEZ0NzNnZU13N1VhTEprYmhMSTcwb0ZNaGhIamF6amZmQ041anE5ejlTOU50Ckt3MEkyaW5RVmtKSUFZMnNLdkptNzJmb20rQ2srSW5Nd0Y4cUh6bTZNMVBXZ2JXdHNlN2h4dDMrcityRk9rd3AKdmU4MVZZam5qSGJYQXN2OUluVHRsSEp0TmFjUm01bUVwS3dwRkRXWk1xRWVMaFNFbWdYMk1TdlNFaG5semZUTQptRkV4aXhjaG5uSWVGV28rNENGMEd3SURBUUFCbzBJd1FEQU9CZ05WSFE4QkFmOEVCQU1DQXFRd0R3WURWUjBUCkFRSC9CQVV3QXdFQi96QWRCZ05WSFE0RUZnUVV1TUJRWDVIMWt2bDROQk5GQWlUQWZSQVhDYUF3RFFZSktvWkkKaHZjTkFRRUxCUUFEZ2dFQkFBcWx4VEJ0cUpheFQ1eXIvbEhPbm1sOUlGeTJsWVRoOUxoNUJDdy9ZQ3FYUFZ6WgpNeVBTSmdTUUpTWm0wZjl2QTc3bEZYeG5qNTRBdE5SN2kva3E0dkJtM0RhWnVzT01uSGF6Vnp6bWdMSHhveUk3Cks5TENrb0dwbHY5aWliVGkybkRQYzVYUUsvbkVPRTNLclpKUlo4YlZnMGlpc0tIUzU1WGs0ajVqMFhvckw3UDUKeVkvdGU5QkY5S1lpWHpMZkVSaElLL25ZWHNkUHViam1wa0t6YnQ5U0k4RExBQlAxWVRWNHdjT2xSYlFFajN4UApnQmtIUjUrZ0JEekZ6RncrbnZYMU9ZM1pRTDFaV21lRTlKSlVQeUtjWWlVYmxFWXBlSzB1M09sSStUUW56aTBtClRCZGF5aU1aZWRVS2M0UUtVZFd4K2VBMkhHZmUwQWNwd2xWUXFBMD0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://172.22.96.133:6443
  name: CID-585ae638bd68
contexts:
- context:
    cluster: CID-585ae638bd68
    user: kubernetes-admin
  name: kubernetes-admin@CID-585ae638bd68
current-context: kubernetes-admin@CID-585ae638bd68
kind: Config
preferences: {}
users:
- name: kubernetes-admin
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURGVENDQWYyZ0F3SUJBZ0lJS3Q4Vnc3NERuUE13RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWdGdzB5TVRFeE1EUXdPVE14TURKYUdBOHlNVEl4TVRBeE1UQTVNekV3TlZvdwpOREVYTUJVR0ExVUVDaE1PYzNsemRHVnRPbTFoYzNSbGNuTXhHVEFYQmdOVkJBTVRFR3QxWW1WeWJtVjBaWE10CllXUnRhVzR3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRRFcvSHhtUThmZVJNTE0KSjVCUVJmZnJsdk1nRWFUODArWERUM1BRcGs5VmVSc0NTaXBudFRkRTBZajM2R2JQUUpOQTYxNWM4Uit0ekFtQwpJcUhLMFVzVjg0UlZtVkREY0M0K3EwSjVPb3pGZ2FoVWE3VkpFeCtRKzV3Wk4wbHIwZ1BBM1JQam1leWRHQkkzCmI5dkNMUCtMWlFnR0QrYmZuZTBQNk9VY0J5eHhOYjhvc0tISFZybW9nRklsR2RxUXkwWHJuWmNwU0Y1SEN4dm8KVFhvN0JVZEYxT3RxVWY4NE44R0xFcGFrUzVCc3pFWDY3SFpIeGZMRVE0T2UrK2t4S2xzbHUrdFNtQUFvb0VYVwowMS96ckdHNXJOb2VHaWc5cFArcGIxS3lFMzl5K1BkS0xEZ0R2V1BINmd0OWdjdlE2WmdBTnl4NzcxZGpsN2l3CmhzZUtCQXVQQWdNQkFBR2pTREJHTUE0R0ExVWREd0VCL3dRRUF3SUZvREFUQmdOVkhTVUVEREFLQmdnckJnRUYKQlFjREFqQWZCZ05WSFNNRUdEQVdnQlM0d0ZCZmtmV1MrWGcwRTBVQ0pNQjlFQmNKb0RBTkJna3Foa2lHOXcwQgpBUXNGQUFPQ0FRRUFtZ0ROdEdZWllFNHJDcEw3TkQreWxIUlJ2WHJKUjNFd01BYUlpTXNnTzBNaURkTmFvRURMCmx6d2d2M3dYckVPS2VWQVUwYW1ES1FPTURHK0lzMG9WVUR0YVN0NEVlR1d1elRXcFF5b3BrVGp6L2FJTTEraHEKK1ZWSEdqbGhWOHU4RFBST0hiWGFwZ3R5dWI2dmI2aHErKzJQZjAzeEVoVDVjNHJ5RWdHSjczajQ1MHZ5aVE1YgpLeENuMzArcG9pUXBDUGtvWU95dVRSTEJiSUNuR3BRNVIxWHFvcU54YnRySXUvQlBRU21aSWpaSzlNQ0hnM3VJCjQrVVZLWlBNYlA5dUhLTkVqMEE0UW5kRVRLRG81UjFjMVd2TnFyUUV1VU0zVHFTa2RrNXU3RmJPaDd2YVNWODQKdXZwRHlpY2JjUUppRUlSbnduM0Z1OHlGZ1Z0ZkFRN3JLQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    client-key-data: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBMXZ4OFprUEgza1RDekNlUVVFWDM2NWJ6SUJHay9OUGx3MDl6MEtaUFZYa2JBa29xClo3VTNSTkdJOStobXowQ1RRT3RlWFBFZnJjd0pnaUtoeXRGTEZmT0VWWmxRdzNBdVBxdENlVHFNeFlHb1ZHdTEKU1JNZmtQdWNHVGRKYTlJRHdOMFQ0NW5zblJnU04yL2J3aXovaTJVSUJnL20zNTN0RCtqbEhBY3NjVFcvS0xDaAp4MWE1cUlCU0pSbmFrTXRGNjUyWEtVaGVSd3NiNkUxNk93VkhSZFRyYWxIL09EZkJpeEtXcEV1UWJNeEYrdXgyClI4WHl4RU9EbnZ2cE1TcGJKYnZyVXBnQUtLQkYxdE5mODZ4aHVhemFIaG9vUGFUL3FXOVNzaE4vY3ZqM1NpdzQKQTcxangrb0xmWUhMME9tWUFEY3NlKzlYWTVlNHNJYkhpZ1FMandJREFRQUJBb0lCQUdkVFRrNndRUDFZdXU3NApET29uMXJJS0NLdmZEeGJjbU04My9vZkhodFdqc1JGMnA4N1VUODNwanhUblE1SlVqUEZrcmlPcFYvcGwyQ1FOCmxRa3ZjaEVJeXcrQThrb2NQbjJzUGZTWjZWSjdzSFZ5bHR5YUxrKzJQaDM0Ym5jOXBzUW8vUWdrMEkzb0pja3oKSDhIQmNzaUNORXNGbFliZ0ZqSFJVMXdYTG9yeDBnS0FCdTlqcjdxVGZtOVp4dmlOYk95Y1RlYVJ4Z2dyU20zMwo0VXdVVkI1ODZXVE9BV0cvOFQrNkVHblQwL1U4ZG5ab1JHdTZJNTZETGtKYTI2Szd1My92cmxUMHB4Qzl4TlQ5CjluTm9kaDljeW1BZUNvN3ZGeW80ME0rL0JHUitOdHFpcmU5KzZIam5kMHdOblBteE40UXdXcHVWYUw0ZDVjTXgKK0xUQTdjRUNnWUVBK243QVVmZ0pMWUk0ZDM0U1NFbXRONkd6WGRqLzd0aXZhekRYTkRvNEQxdlhhaDdjK0UxQQphOS83ckN1ejZTV21KYXZSTmIrdXRvMHRhQkpWQTZRbW84bnJFWjB5TkpML1pzZUJueXdKajFCRVBTbmt0WFArCi9RdUdFNkxSZm4zcGxSNzVKcGdqV0VsSXlSR0ZxaDhGajgrYk01UEpDTWN3Rzg1VHhmQ3NQOThDZ1lFQTI3WDMKbFJPN1BrMWRNRTgzNVJnblN2d1BUQ0U2TlE5U0dGRFhkOU0xbXozZnVoTm1CYXNPbG1IVmRMUllCRkFhSGIvNQpxWnFkN2ZFcXh4ZWJXdy9DTk9vN2g2SEZGUGJvWlpSOWQ1OEdDOWVUM3FwZ0RCalFMTVdLZk03S3VUSUhGUnoyCndlSVlCWHRZenkyQ2NEWlJsTFB6WXAwVmV3SFkxSE5Yb1NzZTZsRUNnWUFPRTc5MUc4NVFPMmcyOXVQS0lqSFUKMVlhQitLYnhZa1lCYlI0NjlpYWVYbGZ0dzh4Qk8vNHAwYzJQOEdqTTZtdTY1RHYrbkVZU1JqN09BWEc3b2FiMgpQMnV4Y3JjV2swZzlHMnNpYWRRanRLd1JEK0NsZmQ1UGxDMDF2MG1zcFNEU1c0bys2Ly9ZZjAzUzF1US9HajB5CnhzVC9FZ2dUTVRaMzZaRjFwei9XMndLQmdRQzc0c1N5YTRrNEloaUs4M090S2hhUC9UVm51Uko1eFh4QzV2OGIKclRhdVp4OG5sT2N0K2JZank4NHFXdjdaMFZaRUVxT0I4b01UczZVTlZKYTZMS083ZElNcjNaOFg2bjJhUUgxNwpDamExY2NrMkpTUzFzNUp5ZHd1UzU1UmRBdmNqaXYxSmwvdEsxTXlCZnoySWtDcjdxMWQ3QVRJWld0Nzk3eFVFCjhrY2h3UUtCZ0VWT0VFbkNjaWVyWnU3TnArTDU1Z2l5dkV3RW5Uek9Bazlxa085YmQ5dFVBTUorOVQ1b3p2dlcKN1lBMzNCditDYTFBUjNwLzNLT2FXY24waFFmK05iMHRqaGhmM3lZWENwVHgydzVaWGVtNHU2L1FLMmZxbk16ZQorQ2pxMGxFNUQ4UVZKa2g5cDZsQkpXcmowZUcxWkg3SC9GcHJNNHRHSG5wKytJd2pJUFpOCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
```

**Comment by 0xff-dev** [comment]
kubeconfig的默认路径是`$HOME/.kube/config`
如果要通过bff环境的oidc认证，需要做如下配置
```yaml
apiVersion: v1
clusters:
- cluster:
   # master节点
    certificate-authority-data: cert-data
    server: https://172.22.96.133:6443
  name: CID-585ae638bd68
- cluster:
   # kube-oidc-proxy的访问地址
    server: https://172.22.96.146:9443
    insecure-skip-tls-verify: true
  name: abc
contexts:
- context:
    cluster: abc
    user: oidc
  name: oidc@abc
#current-context: kubernetes-admin@CID-585ae638bd68
current-context: oidc@abc
kind: Config
preferences: {}
users:
- name: kubernetes-admin
  user:
    client-certificate-data: yy
    client-key-data:  xxx
- name: oidc
  user:
    auth-provider:
      config:
        client-id: client
        client-secret: abc
        id-token:  token
        refresh-token: rtoken
        idp-issuer-url: url
      name: oidc
```

这里有两份连接信息`kubernetes-admin:CID-585ae638bd68`,`oidc:abc` 。
bc-cli在认证通过后，会将token等信息存储到`$HOME/.bestchains/config.yaml`下面。所以这可能需要人为的去修改kubeconfig文件内容(填充oidc的auth-provider信息)。

是否可以将bc-cli认证后得到的信息单独写一个与kubeconfig一致的文件，然后bc-cli连接集群的时候，默认使用这个配置文件。

**Comment by bjwswang** [comment]
需要的配置信息
```yaml
cluster:
   # kube-oidc-proxy的访问地址
    server: https://172.22.96.146:9443
    insecure-skip-tls-verify: true
auth:
    enable: false  # 是否启用oidc验证，也可通过 --enable-auth 参数修改
    client-id: client
    client-secret: abc
    expiry: 1683428084  # oidc token过期时间unix时间戳
    idtoken: eyJhbGciOiJSUzI1NiIsImtpZCI6ImVlZWIyZWUyNzA4ZjU0ZDRkODhjMTMyMzllY2EwYzc2NjM1ODE4NDgifQ.eyJpc3MiOiJodHRwczovL3BvcnRhbC4xNzIuMjIuOTYuMjA5Lm5pcC5pby9vaWRjIiwic3ViIjoiQ2doaWFuZHpkMkZ1WnhJR2F6aHpZM0prIiwiYXVkIjoiYmMtY2xpIiwiZXhwIjoxNjgzNDI3ODY2LCJpYXQiOjE2ODMzNDE0NjYsImF0X2hhc2giOiJxdGhPcmgwa2t1VzRUMDY0MDZwZ1pRIiwiY19oYXNoIjoiejBhczN6MW9QcFJOallvM1JtVWpPZyIsImVtYWlsIjoiYWRtaW5AdGVueGNsb3VkLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJncm91cHMiOlsiaWFtLnRlbnhjbG91ZC5jb20iLCJvYnNldmFiaWxpdHkiLCJyZXNvdXJjZS1yZWFkZXIiLCJiZXN0Y2hhaW5zIl0sIm5hbWUiOiJiandzd2FuZyIsInByZWZlcnJlZF91c2VybmFtZSI6ImJqd3N3YW5nIiwicGhvbmUiOiIiLCJ1c2VyaWQiOiJiandzd2FuZyJ9.OoRvS8lTV5T7hX6IXTIzt9Ne-A44ix10-sYbKOg1Bfk7VX3_WaueMDFjALC7qJ5PZG-m6k_iQZn8dSOgMihwMQAfzJxxpoRbWABSJBS72UZSB18zZKK4mLPKAcEtZUYPFcuQhbR9r12FnokvNnEdd6BrWaIIEGQaYrJgix2HQRdDd6t8s-V3et0dvuWrYLv8HiD06KBUUYNnt1SCI6kuzbzpTLNQFNU86mS7Uq58PmXwXp_MwXZ_PnvmV_GDmg5eEgNLPRmXXryvc4o6Bp_FY5GR8amDqKMwt0m6MWhMOPH2ucYppCi7cUsns-z5068vhDrmTDjguQ6lmwC1m8k-0w
    issuerurl: https://portal.172.22.96.209.nip.io/oidc
    refreshtoken: ChllY3N2a2d6dTM3d2Qzc2F6dnhxb3Q0NHIzEhlhaTZiYnQ0eWZoN3NzcGpjamIyZ2N6eWZ1
```

**Comment by 0xff-dev** [comment]
对，这目前是不考虑证书的情况，如果有证书，需要把证书内容加上。

**Comment by bjwswang** [comment]
> ```yaml
>     client-id: client
> ```
参考
https://github.com/kubernetes/kubectl/blob/master/pkg/cmd/util/factory_client_access.go#L42


证书应该从哪里获取？ 没有证书是不是可以`insecure`模式？

**Comment by bjwswang** [comment]
> 对，这目前是不考虑证书的情况，如果有证书，需要把证书内容加上。

https://github.com/kubernetes/client-go/blob/master/tools/clientcmd/client_config.go#L133 通过kubeconfig初始化RESTConfig， 可以参考

**Comment by 0xff-dev** [comment]
先提交一个版本(不支持自动处理登录信息)，本地创建`$HOME/.bestchains/config.yaml`添加如下内容(文件不存在则创建)，
```yaml
auth:
    clientid: bc-cli
    clientsecret: bc-cli-cli
    enable: false
    expiry: 0
    idtoken: eyJhbGciOiJSUzI1NiIsImtpZCI6ImEwMzQ5ZTI0OWFjYWY4ZDQ0NzZhOGVlMzUyZGQ1YzAyNTIzMGQ2YzIifQ.eyJpc3MiOiJodHRwczovL3BvcnRhbC4xNzIuMjIuOTYuMjA5Lm5pcC5pby9vaWRjIiwic3ViIjoiQ2doaWFuZHpkMkZ1WnhJR2F6aHpZM0prIiwiYXVkIjoiYmZmLWNsaWVudCIsImV4cCI6MTY4Mzg2OTEwMywiaWF0IjoxNjgzNzgyNzAzLCJhdF9oYXNoIjoidVNjNjRyVUZiV1RMQXNWOGZtbnZzdyIsImNfaGFzaCI6InREWmJ2WGhTNTd2Uy1jY2YzUWdMMUEiLCJlbWFpbCI6ImFkbWluQHRlbnhjbG91ZC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiZ3JvdXBzIjpbImlhbS50ZW54Y2xvdWQuY29tIiwib2JzZXZhYmlsaXR5IiwicmVzb3VyY2UtcmVhZGVyIiwiYmVzdGNoYWlucyJdLCJuYW1lIjoiYmp3c3dhbmciLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJiandzd2FuZyIsInBob25lIjoiIiwidXNlcmlkIjoiYmp3c3dhbmcifQ.D_lCIUT82Jg5Bje6WJSFm3fYNkaEU1bV9ZZd72qcsg2vSaI48U7Aa7tzYf6XVPrnme1TBdearuEVcDBAeRGaoEanhf_Cab1XZlsxMce7Xmny1Ih0BQE2AOE3zETNO6CeMXB8h-8tTm7UjAb8UWImTPqcmtW6VjEa5poz8_ayHpju_IYue2i6KWkTwz3AESTsPf8aa_pjk5rJqv1np7ruZjm0HJtfboQOvdbGf0u52y72N65vst431uwujKeU1sfIi5_cjMN0L4_2QG53G2eBuYswfMr9Xa7EOjK4bAUnTiuAIPzyk7P2rDOZerwkWpXZ0KVZm9cE_nOjpZDLw6AVCQ
    issuerurl: https://portal.172.22.96.209.nip.io/oidc
    refreshtoken: Chl1bTc1ZndpZWs1NWRwbnA2b2NlN2ZkcnpsEhllaDJwbzRmNm83bzNwanRibGxpZHd0dzdm
cluster:
    certificateauthority: ""
    disablecompression: false
    insecureskiptlsverify: false
    locationoforigin: ""
    proxyurl: ""
    server: https://172.22.96.146:9443
    tlsservername: ""
saas:
    depository:
        server: ""
```

通过登录bff服务，我们可以得到idtoken，refreshtoken信息，分别填写到`auth.idtoken`, `auth.refreshtoken`。
`auth.issuerurl` 就是oidc服务的issuer-url.
`cluster.server` 对我们环境来说，就是`kube-oidc-proxy`的服务地址。

有了上述配置文件后，本地编译bc-cli。通过下面的命令测试。
```shell
./bc-cli get org
```
