### ISSUE TITLE
add login command 

### ISSUE THREAD

**Issue by bjwswang** [bestchains/bc-cli#3]
1. bc-cli login命令成功后， 生成config文件 `~/.bestchains/config`

```yaml
apiVersion: v1beta1
cluster:
    server: https://172.22.96.133:6443
     name: xxx
user:
  name: xxx
  idtoken: `xxxxx`
saas:
  depository:
      auth: xxx
      server: https://xxxxx:xxx
```

2. 后续所有的CLI调用的参数解析按照如下流程：

1） 首先读取config文件，获取本地配置
2） 读取CLI flags，覆盖本地配置

3. 如果`.auth` 为 `oidc`，则需要将`idtoken`加载到http request header中

**Comment by Abirdcfly** [comment]
配置文件: 
默认路径 `~/.bestchains/config.yaml`，可以通过`--config`参数修改
样例如下：
```yaml
auth:
    enable: false  # 是否启用oidc验证，也可通过 --enable-auth 参数修改
    expiry: 1683428084  # oidc token过期时间unix时间戳
    idtoken: eyJhbGciOiJSUzI1NiIsImtpZCI6ImVlZWIyZWUyNzA4ZjU0ZDRkODhjMTMyMzllY2EwYzc2NjM1ODE4NDgifQ.eyJpc3MiOiJodHRwczovL3BvcnRhbC4xNzIuMjIuOTYuMjA5Lm5pcC5pby9vaWRjIiwic3ViIjoiQ2doaWFuZHpkMkZ1WnhJR2F6aHpZM0prIiwiYXVkIjoiYmMtY2xpIiwiZXhwIjoxNjgzNDI3ODY2LCJpYXQiOjE2ODMzNDE0NjYsImF0X2hhc2giOiJxdGhPcmgwa2t1VzRUMDY0MDZwZ1pRIiwiY19oYXNoIjoiejBhczN6MW9QcFJOallvM1JtVWpPZyIsImVtYWlsIjoiYWRtaW5AdGVueGNsb3VkLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJncm91cHMiOlsiaWFtLnRlbnhjbG91ZC5jb20iLCJvYnNldmFiaWxpdHkiLCJyZXNvdXJjZS1yZWFkZXIiLCJiZXN0Y2hhaW5zIl0sIm5hbWUiOiJiandzd2FuZyIsInByZWZlcnJlZF91c2VybmFtZSI6ImJqd3N3YW5nIiwicGhvbmUiOiIiLCJ1c2VyaWQiOiJiandzd2FuZyJ9.OoRvS8lTV5T7hX6IXTIzt9Ne-A44ix10-sYbKOg1Bfk7VX3_WaueMDFjALC7qJ5PZG-m6k_iQZn8dSOgMihwMQAfzJxxpoRbWABSJBS72UZSB18zZKK4mLPKAcEtZUYPFcuQhbR9r12FnokvNnEdd6BrWaIIEGQaYrJgix2HQRdDd6t8s-V3et0dvuWrYLv8HiD06KBUUYNnt1SCI6kuzbzpTLNQFNU86mS7Uq58PmXwXp_MwXZ_PnvmV_GDmg5eEgNLPRmXXryvc4o6Bp_FY5GR8amDqKMwt0m6MWhMOPH2ucYppCi7cUsns-z5068vhDrmTDjguQ6lmwC1m8k-0w
    issuerurl: https://portal.172.22.96.209.nip.io/oidc
    refreshtoken: ChllY3N2a2d6dTM3d2Qzc2F6dnhxb3Q0NHIzEhlhaTZiYnQ0eWZoN3NzcGpjamIyZ2N6eWZ1
saas:
    depository:
        server: https://bc-saas.172.22.96.209.nip.io
```

下面的gif展示了无需认证，第一次认证和认证后token未过期时的使用场景：
